- hosts: docker
  tasks:
    #  - name: stop container
    #    shell: docker container stop dockeradja2
    #  - name: remove container
    #    shell: docker container rm dockeradja2
    #  - name: docker image removal
    #    shell: docker image rm -f oalalif/gadja-v3.1
     - name: create new container
       shell: docker run -itd --name dockeradja2 oalalif/gadja-v3.1